module Templates where
  
import ClassyPrelude (($), String, LText, forM_, fromString)
import Text.Blaze.Html5
import qualified Text.Blaze.Html5 as H
import Text.Blaze.Html5.Attributes
import Text.Blaze.Html.Renderer.Text

-- * Pages

index :: [(String, String, String)] -> LText
index articlesInfo = 
  renderHtml $
    mainLayout "Ecky Putrady's" $ do
      p $ do
        "You reached Ecky Putrady's Home Page."
        br
        "See "
        a ! href "https://www.linkedin.com/in/eckyputrady/" ! target "_blank" $ " about page "
        "to know more."
      article $ do
        h1 "Article List"
        p $ forM_ articlesInfo $ \(t, d, p) -> do
          H.span ! class_ "date" $ toHtml d
          br
          a ! href (fromString p) $ toHtml t
          br
          br


articlePage aTitle aDate aContent =
  renderHtml $ 
    mainLayout aTitle $ 
      article $ do
        h6 $ toHtml aDate
        h1 $ toHtml aTitle
        aContent

-- * Partials

mainLayout :: String -> Html -> Html
mainLayout pageTitle c =
  docTypeHtml $ do
    head $ do
      meta ! name "viewport" ! content "width=device-width, initial-scale=1.0"
      link ! rel "icon" ! type_ "image/png" ! href "images/favicon.png"
      link ! rel "stylesheet" ! href "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css"
      link ! rel "stylesheet" ! href "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css"
      link ! rel "stylesheet" ! href "https://fonts.googleapis.com/css?family=Open+Sans: 400,700|Lato"
      link ! rel "stylesheet" ! href "/index.css"
      script ! src "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" $ ""
      script "hljs.initHighlightingOnLoad();"
      H.title $ toHtml pageTitle
    body $ do
      header $
        nav $
          h1 $ a ! href "/" $ "Ecky Putrady's"
      section c
      footer $ do
        h3 "Ecky Putrady, 2019"
        h3 $ do 
          "Generated by a "
          a ! href "https://github.com/eckyputrady/eckyputrady.github.io" $ "Haskell static site generator"


